services:
  - type: web
    name: ai-chat-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ai-chat-db
          property: connectionString

databases:
  - name: ai-chat-db
    databaseName: ai_chat
    user: ai_chat_user
    plan: free